
[discovery_crafter]
	#How much FE the Luminous Package Crafter should hold.
	#Range: > 0
	energy_capacity = 5000
	#How much total FE the Luminous Package Crafter should use per operation.
	#Range: > 0
	energy_req = 500
	#How much FE/t maximum the Luminous Package Crafter can use.
	#Range: > 0
	energy_usage = 100
	#Should the Luminous Package Crafter do crafting effects.
	crafting_effects = true
	#Should the Luminous Package Crafter draw energy from ME systems.
	draw_me_energy = true

[attunement_crafter]
	#How much FE the Starlight Package Crafting Altar should hold.
	#Range: > 0
	energy_capacity = 5000
	#How much total FE the Starlight Package Crafting Altar should use per operation.
	#Range: > 0
	energy_req = 500
	#How much FE/t maximum the Starlight Package Crafting Altar can use.
	#Range: > 0
	energy_usage = 100
	#Should the Starlight Package Crafting Altar require the structure and do crafting effects.
	requires_structure = true
	#Should the Starlight Package Crafting Altar draw energy from ME systems.
	draw_me_energy = true

[constellation_crafter]
	#How much FE the Celestial Package Crafting Altar should hold.
	#Range: > 0
	energy_capacity = 5000
	#How much total FE the Celestial Package Crafting Altar should use per operation.
	#Range: > 0
	energy_req = 500
	#How much FE/t maximum the Celestial Package Crafting Altar can use.
	#Range: > 0
	energy_usage = 100
	#Should the Celestial Package Crafting Altar require the structure and do crafting effects.
	requires_structure = true
	#Should the Celestial Package Crafting Altar draw energy from ME systems.
	draw_me_energy = true

[trait_crafter]
	#How much FE the Iridescent Package Crafting Altar should hold.
	#Range: > 0
	energy_capacity = 5000
	#How much total FE the Iridescent Package Crafting Altar should use per operation.
	#Range: > 0
	energy_req = 500
	#How much FE/t maximum the Iridescent Package Crafting Altar can use.
	#Range: > 0
	energy_usage = 100
	#Should the Iridescent Package Crafting Altar require the structure and do crafting effects.
	requires_structure = true
	#Should the Iridescent Package Crafting Altar draw energy from ME systems.
	draw_me_energy = true

